In [1]:
import lasio
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)

In [8]:
selected_columns = [
    "YYYY/MM/DD",
    "HH:MM:SS",
    "Hole Depth (feet)",
    "Bit Depth (feet)",
    "Rate Of Penetration (ft_per_hr)",
    "Weight on Bit (klbs)",
    "Hook Load (klbs)",
    "Rotary RPM (RPM)",
    "Standpipe Pressure (psi)",
    "Rotary Torque (kft_lb)",
    "Differential Pressure (psi)",
    "Flow (flow_percent)",
    "Total Pump Output (gal_per_min)",
    "Pason Gas (percent)",
    "On Bottom (unitless)",
    "Hole Diameter (in)",
    "Bit RPM (RPM)",
    "Bit Torque (kft_lb)",
    "EDR Instantaneous ROP (ft_per_hr)",
    "On Bottom ROP (ft_per_hr)",
    "Surface Stick Slip Index (percent)",
    "MWD Temp (Fahrenheit)",
    "Azimuth (degrees)",
    "Inclination (degrees)",
    "Temp IN (Degrees)",
    "Temp OUT (Degrees)",
    "AutoDriller WOB (klbs)",
    "AutoDriller Torque (kft_lb)",
    "Top Drive Rotary (RPM)",
    "Top Drive Torque (kft_lb)",
    "DAS BHA Stick Slip (unitless)",
    "DAS Bit Stick Slip (unitless)",
    "DAS MSE (ksi)",
    "DAS Downhole MSE (ksi)",
    "DAS ROP (ft_per_hr)",
    "DAS Recommended DIFFP (psi)",
    "DAS Recommended ROP (ft_per_hr)",
    "DAS Recommended RPM (RPM)",
    "DAS Recommended WOB (klbs)",
    "Depth of Cut (in)",
    "dexponent (log)",
    "Mechanical Specific Energy (ksi)",
    "TTS Mechanical Specific Energy (ksi)",
    "Relative MSE (unitless)"
]

In [9]:
df1=pd.read_csv("27029986-3.csv", usecols=selected_columns)

In [10]:
df2=pd.read_csv("27029986-4.csv", usecols=selected_columns)

In [11]:
df3=pd.read_csv("27029986-5.csv", usecols=selected_columns)

In [12]:
df4=pd.read_csv("27029986-6.csv", usecols=selected_columns)

In [13]:
print("1st Data")
print("___________________")
print("Size:", df1.size)
print("Shape:", df1.shape)
print("\n")
print("2nd Data")
print("___________________")
print("Size:", df2.size)
print("Shape:", df2.shape)
print("\n")
print("3rd Data")
print("___________________")
print("Size:", df3.size)
print("Shape:", df3.shape)
print("\n")
print("4th Data")
print("___________________")
print("Size:", df4.size)
print("Shape:", df4.shape)

1st Data
___________________
Size: 25819552
Shape: (586808, 44)


2nd Data
___________________
Size: 26580004
Shape: (604091, 44)


3rd Data
___________________
Size: 26518492
Shape: (602693, 44)


4th Data
___________________
Size: 31353960
Shape: (712590, 44)

In [14]:
df_list=[df1,df2,df3,df4]

for df in df_list:
    print("Record")
    print("Start Date: ", df["YYYY/MM/DD"][0])
    print("End Date: ",   df["YYYY/MM/DD"][df.shape[0]-1])
    print("Start Hole Depth: ", df["Hole Depth (feet)"][0])
    print("End Hole Depth: ", df["Hole Depth (feet)"][df.shape[0]-1])
    print("____________________________")

Record
Start Date:  2021/02/08
End Date:  2021/02/14
Start Hole Depth:  174.5
End Hole Depth:  4701.7
____________________________
Record
Start Date:  2021/02/15
End Date:  2021/02/21
Start Hole Depth:  4702.0
End Hole Depth:  7620.0
____________________________
Record
Start Date:  2021/02/22
End Date:  2021/02/28
Start Hole Depth:  7620.0
End Hole Depth:  9145.0
____________________________
Record
Start Date:  2021/03/01
End Date:  2021/03/09
Start Hole Depth:  9145.0
End Hole Depth:  9034.0
____________________________

### CONCATING ALL DATA

In [20]:
df=pd.concat([df1,df2,df3,df4], ignore_index=True)

In [21]:
df.head()

,YYYY/MM/DD,HH:MM:SS,Hole Depth (feet),Bit Depth (feet),Rate Of Penetration (ft_per_hr),Weight on Bit (klbs),Hook Load (klbs),Rotary RPM (RPM),Standpipe Pressure (psi),Rotary Torque (kft_lb),Differential Pressure (psi),Flow (flow_percent),Total Pump Output (gal_per_min),Pason Gas (percent),AutoDriller Torque (kft_lb),AutoDriller WOB (klbs),Azimuth (degrees),Bit RPM (RPM),Bit Torque (kft_lb),DAS BHA Stick Slip (unitless),DAS Bit Stick Slip (unitless),DAS Downhole MSE (ksi),DAS MSE (ksi),DAS Recommended DIFFP (psi),DAS Recommended ROP (ft_per_hr),DAS Recommended RPM (RPM),DAS Recommended WOB (klbs),DAS ROP (ft_per_hr),Depth of Cut (in),dexponent (log),EDR Instantaneous ROP (ft_per_hr),Hole Diameter (in),Inclination (degrees),Mechanical Specific Energy (ksi),MWD Temp (Fahrenheit),On Bottom (unitless),On Bottom ROP (ft_per_hr),Relative MSE (unitless),Surface Stick Slip Index (percent),Temp IN (Degrees),Temp OUT (Degrees),Top Drive Rotary (RPM),Top Drive Torque (kft_lb),TTS Mechanical Specific Energy (ksi)
0,2021/02/08,04:30:00,174.5,98.9,0.0,0.0,56.8,0.03,0.0,0.005,0.0,0.0,0.0,-999.25,0.005,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,0.0,0.0,-999.25,-999.25,41.96,42.44,0.0,0.005,-999.25
1,2021/02/08,04:30:01,174.5,98.9,0.0,0.0,56.8,0.03,0.0,0.005,0.0,0.0,0.0,-999.25,0.005,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,0.0,0.0,-999.25,-999.25,41.96,42.44,0.0,0.005,-999.25
2,2021/02/08,04:30:02,174.5,98.9,0.0,0.0,56.8,0.03,0.0,0.005,0.0,0.0,0.0,-999.25,0.005,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,0.0,0.0,-999.25,-999.25,41.96,42.44,0.0,0.005,-999.25
3,2021/02/08,04:30:03,174.5,98.9,0.0,0.0,56.8,0.03,0.0,0.005,0.0,0.0,0.0,-999.25,0.005,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,0.0,0.0,-999.25,-999.25,41.96,42.44,0.0,0.005,-999.25
4,2021/02/08,04:30:04,174.5,98.9,0.0,0.0,56.8,0.03,0.0,0.005,0.0,0.0,0.0,-999.25,0.005,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,0.0,-999.25,0.0,-999.25,-999.25,-999.25,-999.25,0.0,0.0,-999.25,-999.25,41.98,42.51,0.0,0.005,-999.25

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Hole Depth (feet),2506182.0,6.437752e+03,2.631163e+03,-999.25,4502.600,7207.700,9034.000,9.147800e+03
Bit Depth (feet),2506182.0,4.536357e+03,3.091486e+03,-999.25,1250.600,4646.200,7184.000,9.147800e+03
Rate Of Penetration (ft_per_hr),2506182.0,2.512671e+01,9.821430e+01,-999.25,0.000,0.000,18.980,1.114593e+04
Weight on Bit (klbs),2506182.0,1.897455e+01,2.897381e+01,-999.25,0.000,0.000,41.400,1.920000e+02
Hook Load (klbs),2506182.0,9.318635e+01,6.106482e+01,-999.25,39.000,65.300,139.600,3.921000e+02
Rotary RPM (RPM),2506182.0,1.626642e+01,2.818419e+01,-999.25,0.000,0.030,39.250,1.137900e+02
Standpipe Pressure (psi),2506182.0,1.184301e+03,1.499623e+03,-999.25,0.000,0.000,2994.750,5.298750e+03
Rotary Torque (kft_lb),2506182.0,1.928769e+00,1.504976e+01,-999.25,0.000,0.000,4.486,4.880900e+01
Differential Pressure (psi),2506182.0,-6.947406e+02,1.131267e+03,-5138.83,-1501.010,-124.330,130.950,5.119480e+03
Flow (flow_percent),2506182.0,2.865129e+01,6.491172e+01,-999.25,0.940,6.630,68.760,1.344300e+02
Total Pump Output (gal_per_min),2506182.0,2.559084e+02,3.110420e+02,-999.25,0.000,0.000,660.570,1.772770e+03
Pason Gas (percent),2506182.0,-9.992500e+02,0.000000e+00,-999.25,-999.250,-999.250,-999.250,-9.992500e+02
AutoDriller Torque (kft_lb),2506182.0,1.942515e+00,1.520119e+01,-999.25,0.000,0.000,4.527,4.876000e+01
AutoDriller WOB (klbs),2506182.0,7.763777e+01,6.833131e+01,-999.25,22.390,48.890,149.800,2.818800e+02
Azimuth (degrees),2506182.0,-4.293194e+02,6.024158e+02,-999.25,-999.250,-999.250,207.220,2.692900e+02
Bit RPM (RPM),2506182.0,7.518065e+01,9.243836e+01,-999.25,0.000,0.000,183.000,4.720000e+02
Bit Torque (kft_lb),2506182.0,-5.444168e+01,2.268033e+02,-999.25,0.000,0.000,0.000,1.800000e+01
DAS BHA Stick Slip (unitless),2506182.0,-5.273182e+02,4.989096e+02,-999.25,-999.250,-999.250,0.040,6.790000e+00
DAS Bit Stick Slip (unitless),2506182.0,-5.969788e+02,4.900609e+02,-999.25,-999.250,-999.250,0.014,1.441000e+00
DAS Downhole MSE (ksi),2506182.0,-7.139548e+02,4.514603e+02,-999.25,-999.250,-999.250,0.142,4.924700e+01
DAS MSE (ksi),2506182.0,-7.158759e+02,1.425260e+03,-999.25,-999.250,-999.250,0.293,9.123648e+05
DAS Recommended DIFFP (psi),2506182.0,-9.992500e+02,0.000000e+00,-999.25,-999.250,-999.250,-999.250,-9.992500e+02
DAS Recommended ROP (ft_per_hr),2506182.0,-9.992456e+02,2.093454e+00,-999.25,-999.250,-999.250,-999.250,0.000000e+00
DAS Recommended RPM (RPM),2506182.0,-9.992455e+02,2.124879e+00,-999.25,-999.250,-999.250,-999.250,1.500000e+01
DAS Recommended WOB (klbs),2506182.0,-9.992314e+02,4.379445e+00,-999.25,-999.250,-999.250,-999.250,4.904700e+01
DAS ROP (ft_per_hr),2506182.0,-6.985454e+02,4.783025e+02,-999.25,-999.250,-999.250,15.403,1.072110e+04
Depth of Cut (in),2506182.0,2.414143e+03,8.579793e+05,-999.25,0.000,0.000,0.020,3.738635e+08
dexponent (log),2506182.0,-6.867872e+02,4.636628e+02,-999.25,-999.250,-999.250,0.460,9.090000e+00
EDR Instantaneous ROP (ft_per_hr),2506182.0,2.522232e+01,1.011858e+02,-999.25,0.000,0.000,18.298,1.114593e+04
Hole Diameter (in),2506182.0,-4.645406e+00,1.180044e+02,-999.25,8.750,8.750,8.750,1.250000e+01
Inclination (degrees),2506182.0,-5.151600e+02,5.016526e+02,-999.25,-999.250,-999.250,3.100,9.970000e+01
Mechanical Specific Energy (ksi),2506182.0,5.235553e+04,4.076321e+07,-999.25,-999.250,-999.250,0.600,4.389070e+10
MWD Temp (Fahrenheit),2506182.0,-9.972019e+02,4.836977e+01,-999.25,-999.250,-999.250,-999.250,1.760000e+02
On Bottom (unitless),2506182.0,3.224064e-01,2.568946e+00,-999.25,0.000,0.000,1.000,1.000000e+00
On Bottom ROP (ft_per_hr),2506182.0,2.512671e+01,9.821430e+01,-999.25,0.000,0.000,18.980,1.114593e+04
Relative MSE (unitless),2506182.0,2.216981e+08,1.891851e+10,-999.25,-999.250,-999.250,29.000,3.603484e+12
Surface Stick Slip Index (percent),2506182.0,-7.449276e+02,4.367815e+02,-999.25,-999.250,-999.250,0.800,1.000000e+02
Temp IN (Degrees),2506182.0,7.902271e+01,5.173164e+01,-999.25,55.980,83.710,103.040,2.995800e+02
Temp OUT (Degrees),2506182.0,8.839396e+01,7.397103e+01,-999.25,65.410,92.100,119.580,6.303800e+02
Top Drive Rotary (RPM),2506182.0,1.626047e+01,2.800628e+01,-999.25,0.000,0.000,39.000,1.160000e+02
Top Drive Torque (kft_lb),2506182.0,1.952998e+00,1.467984e+01,-999.25,-0.009,-0.005,4.527,4.876000e+01
TTS Mechanical Specific Energy (ksi),2506182.0,1.510803e+04,1.272685e+07,-999.25,-999.250,-999.250,0.000,1.754462e+10